language: r
cache: packages
dist: xenial
latex: false
warnings_are_errors: false

r:
- release
- oldrelease
- devel

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libpoppler-cpp-dev
      - libtesseract-dev
      - libleptonica-dev
      - tesseract-ocr-eng
      - r-cran-rgdal
      - r-cran-maptools
      - r-cran-raster
      - r-cran-rgeos
      - r-cran-MASS
      - libfftw3-dev
      - cargo
      
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh