language: r
cache: packages
dist: xenial
latex: false
warnings_are_errors: false

r:
- release
- oldrelease
- devel

addons:
  apt:
    update: true
    packages:
      - libgdal-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libjq-dev
      - libv8-dev
      
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh