language: r
cache: packages
pandoc_version: 1.19.2.1

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/jq'
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
     - ccache
     - libprotobuf-dev
     - protobuf-compiler
     - libv8-dev
     - libjq-dev
     - libudunits2-dev
     - libproj-dev
     - libgeos-dev
     - libgdal-dev
     - libnetcdf-dev
     - netcdf-bin

install:
  - R -e "install.packages('remotes')"
  - R -e "install.packages('tinytex')"
  - R -e "tinytex::install_tinytex()"
  - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh