language: r
cache: packages
pandoc_version: 1.19.2.1

install:
  - R -e "install.packages('remotes')"
  
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
