language: r
cache: packages
pandoc_version: 1.19.2.1

repos: 
  CRAN: https://cran.rstudio.com
  rforge: http://R-Forge.R-project.org

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh